### ISSUE TITLE
DELPHI API forecasts are not loading on the site

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#12]
@lepisma says "Some error in (at least one) metadata file in new PR." Not sure what these are, If you specify exactly, @brookslogan might be able to fix and resubmit.

**Comment by brookslogan** [comment]
There are also some inconsistencies with the column types the other submissions and the template.  I have updated the Value column to be numeric like in the other spreadsheets (with point predictions of "none" represented as NAs).  That should avoid some "NAs introduced by coercion" warnings, but I assume that is not the main issue.  I will look to see if I find any obvious issues in the metadata files.

**Comment by lepisma** [comment]
@brookslogan there was some issue with quoting `:`. I added a PR fixing that (#15). I don't think the issue is present with *all* yaml parsers, the variant I was using ([js-yaml](https://github.com/nodeca/js-yaml)) broke though.

**Comment by nickreich** [comment]
So, the quoting issue is fixed but the files are still not loading? Is there another issue at play here?

**Comment by lepisma** [comment]
@nickreich you would have to pull in PR #15. Also PR #13 adds tests for further pull requests and PR #16 fixes a metadata.txt naming issue.
