### ISSUE TITLE
add statcounter to site.

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#124]

**Comment by lepisma** [comment]
@nickreich can you email me the statcounter script to put in here? Current version uses the script for `http://reichlab.io/flusight` and so might not be logging the visits.

**Comment by lepisma** [comment]
Added the snippet. Can you confirm if it works?

**Comment by nickreich** [comment]
hmm.. not working right now. I loaded the site (and you did earlier today) but the statcounter still not showing any hits.

**Comment by lepisma** [comment]
Try now? I fixed an issue which was stopping the correct variables to get exposed. This should be it.

**Comment by nickreich** [comment]
working.
