### ISSUE TITLE
CUBMA EW15 onset bin issue

### ISSUE THREAD

**Issue by lepisma** [FluSightNetwork/cdc-flusight-ensemble#132]
The file `real-time-component-models/CUBMA/EW15-2018-CUBMA.csv` has the following row which fails to be _verified_ from the [FluSight](https://github.com/jarad/flusight)'s verify function:

```
US National,Season onset,Bin,week,NaN,NaN,0
```

Basically have to change the `NaN` to `none`.

@tkcy letting you know in case there is some automation bug on your side.

**Comment by tkcy** [comment]
Sorry about that, and thanks for fixing! Our work flow got messed up this week, will be back to normal for ew16.

sent from mobile device
