### ISSUE TITLE
check updated team and model names/abbreviations

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#18]
We updated the metadata template so the information was more efficiently captured. @brookslogan @tkcy can you check your metadata files to make sure that I didn't screw anything up in the transition?

**Comment by brookslogan** [comment]
There is a trailing space on the first line of each (Delphi) metadata file, so the team name might be parsed as "Delphi ".  Other than that, the updated metadata files look good; thanks for changing these to the new format for us.

**Comment by tkcy** [comment]
Looks good - thanks!

**Comment by lepisma** [comment]
`ReichLab_kde/metadata.txt` has model_abbr as KCDE. I believe that should be KDE.

**Comment by nickreich** [comment]
Fixed. thanks, good catch.
