### ISSUE TITLE
are historical ILI rates (known at time T) available?

### ISSUE THREAD

**Issue by randomgambit** [FluSightNetwork/cdc-flusight-ensemble#197]
Hello there, I am cross-posting this issue https://github.com/cmu-delphi/delphi-epidata/issues/18 as it might be relevant.

I wonder if `cdc-flusight-ensemble` keeps track of the unrevised ILI rates at the HHI or state level. Indeed, the data shown here https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html only shows the `final and revised` ILI rates. These were not necessarily known at each point in time. 

Does that make sense?
Thanks a lot!!

**Comment by lcbrooks** [comment]
Provisional ILINet data are available via the Delphi-Epidata API.  Further discussion is in the linked issues [cmu-delphi/delphi-epidata#18](https://github.com/cmu-delphi/delphi-epidata/issues/18) and [cmu-delphi/delphi-epidata#19](https://github.com/cmu-delphi/delphi-epidata/issues/19); see also the API's [README](https://github.com/cmu-delphi/delphi-epidata/blob/master/README.md) and the [FluSight-Network guidelines](https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/guidelines.md) which discuss pulling provisional ILINet data for use in preparing pseudoprospective common development-set forecasts.
