### ISSUE TITLE
Confirm that target-multivals are created based on data as of the end of season

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#203]
I can't quite understand what this code is doing, but wanted to confirm that the file `./scripts/calculate-targets.R` is computing the "ground truth" based on the data as of the end of each season, not based on the current data whenever we run the script. @brookslogan can you confirm this? I think we want to be calculating the targets based on how it is at the end of each season because this is more true to the CDC evaluation and application.

https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/a2ed026ad766fa18842a3169fc67ae7b7dff0d78/scripts/calculate-targets.R#L1

**Comment by brookslogan** [comment]
Sorry, no, this is using the current data, not the data at the end of each season.  Looking at this now.
