### ISSUE TITLE
Incomplete forecast file

### ISSUE THREAD

**Issue by NutchaW** [FluSightNetwork/cdc-flusight-ensemble#210]
HHS region 9 forecasts and a point forecast for HHS Region 1 Season onset are missing in this file @srinivvenkat

`FluSight::verify_entry_file("model-forecasts/component-models/FluX_LSTM/EW10-2014-FluX_LSTM.csv",challenge = "ilinet")`
Consider forecasting for these locations: HHS Region 9
Warning message:
In FluSight::verify_point(entry) :
  WARNING: Missing point predictions detected in HHS Region 1 Season onset. 
Please take a look at the generate_point_forecasts function.

**Comment by srinivvenkat** [comment]
Thank you for catching this and letting us know. The missing Region 9 predictions might be because of failed job. Will rerun and update.

**Comment by srinivvenkat** [comment]
As for the Region 1 onset, it seems like the point forecast itself is present, but the model seems to be predicting 'no onset' (will investigate this separately) and hence the point forecast is left blank. This is true in a few other EWs in the same season and region.

Just consulted the guidance document. Will change the point prediction to 'NA' in those files.

**Comment by srinivvenkat** [comment]
Could you confirm that if we fill point prediction for onset with 'NA' this error would not occur? We are testing locally using FluSight's verify_submit function (which calls verify_point.R), and we still get a missing point prediction warning when the onset prediction is NA or "NA".

**Comment by nickreich** [comment]
I think it will be ok. It is hard for us to tell until we run the script though. Can you push in a new version and we will test it ASAP?

**Comment by srinivvenkat** [comment]
Thanks Nick. Have pushed a version which has the missing Region 9, and also has no onset point prediction as 'NA's. Please let us know if the warning persists.

Meanwhile, we've identified the bug that was causing several of these 'no onset' predictions (mismatch of region baselines in onset estimation). We've fixed it and are rerunning the models. Once they're done, we can push the updated results. Hope there's still time to retrain them.

Sorry for the inconvenience.
