### ISSUE TITLE
Error in EW49 2018 CU_EAKFC_SIRS data format

### ISSUE THREAD

**Issue by katiehouse3** [FluSightNetwork/cdc-flusight-ensemble#214]
There is a formatting error in this following forecast file:

[https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/model-forecasts/component-models/CU_EAKFC_SIRS/EW49-2018-CU_EAKFC_SIRS.csv](https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/model-forecasts/component-models/CU_EAKFC_SIRS/EW49-2018-CU_EAKFC_SIRS.csv)

@tkcy Would you be able to check if all seasons, regions, and targets have estimates in the correct format for this forecast?  I am unable to spot the exact issue. The error that I am getting is that there may be some `undefined` value or missing prediction. Thank you!

**Comment by katiehouse3** [comment]
@tkcy - @nickreich and I found the error is because the point estimate for Reason 6 Season onset is missing for this forecast. Would you be able to re-upload this forecast with a Reason 6 Season onset point estimate?

**Comment by tkcy** [comment]
Thanks, should be fixed.

**Comment by NutchaW** [comment]
merged. will let you know if there is any issues.
