### ISSUE TITLE
Error in Protea_Kudu Forecast Formatting

### ISSUE THREAD

**Issue by katiehouse3** [FluSightNetwork/cdc-flusight-ensemble#215]
@craigjmcgowan could you please use decimal notation instead of scientific notation for all Protea_Kudu forecasts? The visualization is not compatible with scientific notation predictions.

<img width="514" alt="Screen Shot 2019-10-17 at 12 38 18 PM" src="https://user-images.githubusercontent.com/26775314/67029329-160d8680-f0db-11e9-88b7-d37d0e4bad22.png">

Thanks!

**Comment by craigjmcgowan** [comment]
Sure - I'll fix tonight and resubmit

**Comment by katiehouse3** [comment]
Thank you so much!

**Comment by craigjmcgowan** [comment]
Re-pushed the Kudu forecasts in decimal notation. Closing this but if it's not resolved please reopen and let me know!
