### ISSUE TITLE
Protea_Kudu forecasts have unexpected indentation in the ‘value’ column

### ISSUE THREAD

**Issue by Khoale1096** [FluSightNetwork/cdc-flusight-ensemble#233]
I noticed some forecasts of Kudu have tab indentation in the 'value' column like in the image:
<img width="479" alt="Screenshot (173)" src="https://user-images.githubusercontent.com/31902663/68406256-84c88780-014f-11ea-994b-b62445ed303d.png">
According to the common format of csv https://tools.ietf.org/html/rfc4180#page-2, "Spaces are considered part of a field and should not be ignored.". Therefore when the scripts read this value field, they get values with leading white spaces, rather than just the float numbers. Therefore I think this should be fixed.
I've seen this issues in the real-time forecasts this season, as well as the retroactive forecasts of last season for Kudu.

**Comment by craigjmcgowan** [comment]
I believe this is fixed for the EW44 forecasts - it's a result of coercing the Value field to character in R as a result of #215. 

I just used `trimws` in R on the Value field. Do you need me to adjust the training forecasts as well?

**Comment by nickreich** [comment]
I wondered if it wasn't tied to the other formatting issue. If it's not too much trouble, would be great if you could adjust the training forecasts as well.

**Comment by craigjmcgowan** [comment]
I can do that. May be a few days before I have time but will update before next week's submission
