### ISSUE TITLE
why are basis regression PIs not covering the point estimates?

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#24]
![image](https://user-images.githubusercontent.com/1280767/30790472-0f8c75bc-a17a-11e7-8417-0a564e17bd2e.png)

**Comment by brookslogan** [comment]
Thanks for pointing this out; this is a bug with the forecasts, not the visualizer.  Both basis regression and the "uniform" distribution have bugs due to boundary bias issues with a post-processing kernel smoothing step.  I hope to fix this issue and resubmit the Delphi retrospective forecasts.
