### ISSUE TITLE
minor fixes to new scores table

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#25]
- [x] remove disclaimer about "final data" at bottom
- [x] add explicit "NA" for missing scores
- [ ] @brookslogan why are scores for Delphi Uniform? related to #24 ?
- [x] add sorting feature on table
- [ ] For this table, why does only week 1 have a bold "first place"?
- [ ] Once I am at the scores tab, I am unable to re-navigate back to another tab.

![image](https://user-images.githubusercontent.com/1280767/30915761-c16eb9b0-a365-11e7-93fc-fe701b39704a.png)

**Comment by lepisma** [comment]
Adding another items:
- [ ] Default to log score?
- [ ] Fix the height of table similar to plots

Possible reason for the last two issues. The `Nan`s (which are not displayed in this version) are not expected by the table, leading to a fatal error which freezes the whole thing. For example, the tab switching works if you never go to a selection with Nan in it. Will fix this.
