### ISSUE TITLE
reorganize file and folder structure

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#31]
Need to create three sets of folders for forecasts
 - component model forecasts (to be included in visualization, scores)
 - CV ensemble model forecasts (to be included in scores)
 - Real-time ensemble model forecasts (to be included in visualization)

Also, this will require changing file-paths in other scripts (visualizations, score calculations, etc...) that are dependent on these files.

**Comment by lepisma** [comment]
Should these go inside another directory in root so that the final structure looks like the following:
```sh
├── flusight-deploy
│   ├ ...
├── model-forecasts
│   ├── component-models
│   ├── cv-ensemble-models
│   └── real-time-ensemble-models
├── plots
├── scores
├── ...
```

**Comment by nickreich** [comment]
sounds good to me.
