### ISSUE TITLE
create "complete-models" file with columns for model-id, team_name, and model-file-path

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#35]

**Comment by lepisma** [comment]
I added `model-id-map` files in each of the three model type directories.
A sample is here.

```csv
model-id,model-dir
CU-BMA,CUBMA
CU-EAKFC,CUEAKFC
Delphi-BasisRegression,Delphi_BasisRegression_PackageDefaults
Delphi-DeltaDensity1,Delphi_DeltaDensity_PackageDefaults
...
```

The first column is model id (`team_abbr-model_abbr`) and next is the folder (adjacent to the csv. I can change it to the complete path relative to repo root if needed). These mappings are not per season and doesn't have any sense about which models are complete in any season.

**Comment by lepisma** [comment]
Update:
I added code that skips model mapping for _incomplete_ models. This means that the new file (which is `complete-modelids.csv` now) has three columns:
```csv
season,model-id,model-dir
2010/2011,Delphi-BasisRegression,Delphi_BasisRegression_PackageDefaults
2010/2011,Delphi-DeltaDensity1,Delphi_DeltaDensity_PackageDefaults
2010/2011,Delphi-EmpiricalBayes1,Delphi_EmpiricalBayes_Cond4
2010/2011,Delphi-EmpiricalBayes2,Delphi_EmpiricalBayes_PackageDefaults
...
```

If a model hasn't provided submission files from week 40 to week 20 (inclusive) for each season, then that doesn't get mentioned in that season. This is a harsh test and some models get skipped completely (CU*, RL_KCDE). Maybe there is some off by one thing? All of the models are not submitting exactly 33 (or 34 for season with 53 weeks) files per season?

**Comment by nickreich** [comment]
There are some missing files, so this is not too harsh of a test.

**Comment by nickreich** [comment]
Would it be possible, for now, to include both versions of this file? The `model-id-map` and the `complete-modelids`? The score calculations do not ignore incomplete models, so we need the map for all models. But seeing which are complete is really useful too. Maybe we could use `model-id-map` and add a single column with an 0/1 indicator for "complete".

**Comment by lepisma** [comment]
Added the automation script for `model-id-map.csv` file. This file now also has column specifying whether the model is complete (in all the seasons).
