### ISSUE TITLE
unknown issue with new CU files

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#45]
Travis is saying `# Some error in CU-EAKFC_SEIRS 2011-19 for HHS Region 4, Season onset`. Is there some obvious error with this entry file?

FWIW - the (long) transcripts from the site builds (including errors) can be seen here:
https://travis-ci.org/FluSightNetwork/cdc-flusight-ensemble

**Comment by lepisma** [comment]
The file [EW19-2011-CU_EAKFC_SEIRS.csv](https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/model-forecasts/component-models/CU_EAKFC_SEIRS/EW19-2011-CU_EAKFC_SEIRS.csv) doesn't have all the required rows.

Specifically, its missing 'Season onset' bins for 'HHS Region 4'. Might have other missing items too.

**Comment by lepisma** [comment]
Some more information. Its only one file [EW-19-2011-CU_EAKFC_SEIRS.csv](https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/model-forecasts/component-models/CU_EAKFC_SEIRS/EW19-2011-CU_EAKFC_SEIRS.csv) and its missing bins for all the targets except `1 wk ahead`.

**Comment by nickreich** [comment]
From @lepisma : 
```
The file https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/model-forecasts/component-models/CU_EAKFC_SEIRS/EW19-2011-CU_EAKFC_SEIRS.csv doesn't have all the required rows. 
Specifically, its missing 'Season onset' bins for 'HHS Region 4'. Might have other missing items too.
```

**Comment by nickreich** [comment]
I put in a temporary fix for this, replacing EW-19-2011-CU_EAKFC_SEIRS.csv with EW-18-2011-CU_EAKFC_SEIRS.csv
