### ISSUE TITLE
CUBMA model missing files

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#6]
Some files from the CUBMA model are missing. When running the validate_predictions file, I got an error because the `CUBMA/EW51-2010-CUBMA.csv` file doesn't exist. there may be others that don't exist as well, this was just the first one it ran across.

**Comment by nickreich** [comment]
This issue is for @tkcy

**Comment by tkcy** [comment]
Sorry about that - naming issue, should be fixed now.

We only go up to EW18 (EW17 in 2015 since 53 weeks in 2014).  This should be enough for this year's contest, which does EW43 through EW18.

**Comment by nickreich** [comment]
I'm bumping this issue up, since we still are missing EW40-42, and EW19-20 files for CU models.

**Comment by nickreich** [comment]
Also, as noted by @tcky but missed by me in my first pass, EW18 in 2015 is missing for CU files.
