### ISSUE TITLE
minor discrepancy in spot-checked distributions

### ISSUE THREAD

**Issue by tkcy** [FluSightNetwork/cdc-flusight-ensemble#60]
I'm getting very small differences in my spot-checks of ensemble distributions, particularly in 1-4 week ahead forecasts with TRW, TW, TTW [see example image below)

Very possibly a problem on my end, which I'm checking, but also wanted to ask whether any rounding happens in creating the new distribution?

![examplespotcheck](https://user-images.githubusercontent.com/6554965/32069458-3d0863b6-ba57-11e7-8249-791aeb7aeb1d.png)

**Comment by nickreich** [comment]
These are really helpful, thanks for putting them together! I don't think there is any rounding going on. Have you downloaded the most recent version of the repository and generated this figure from that? It is possible, with all the weight and file updating yesterday, that you obtained a set of weights or ensemble files that were not completely synced up. Which could explain a small discrepancy if the weights were a bit different from one iteration to the next...

**Comment by tkcy** [comment]
Discrepancy is resolved.  I'll check again, more systematically, once the latest forecast files are incorporated.

**Comment by nickreich** [comment]
@tkcy latest forecasts are incorporated.

**Comment by tkcy** [comment]
Distributions match to within 10^-16 for all weeks/years/targets/regions
