### ISSUE TITLE
Fix visualization of week targets ranges

### ISSUE THREAD

**Issue by lepisma** [FluSightNetwork/cdc-flusight-ensemble#77]
![image](https://user-images.githubusercontent.com/2487306/32702464-9ac9cc02-c7df-11e7-866c-83b74a32a49c.png)

Point predictions are outside the range. Maybe this is because the visualizer prefers point prediction written in the `Point` row which is not matching with the distributions in the csvs.

**Comment by nickreich** [comment]
I think this was a bug in the forecasts. closed by d4ac828f11c28a36bb374aa8acf20a737e196247
