### ISSUE TITLE
Funny point forecasts for peak week

### ISSUE THREAD

**Issue by craigjmcgowan** [FluSightNetwork/cdc-flusight-ensemble#79]
The point forecast for US National peak week doesn't match up at all with the underlying distribution. The point forecast is for week 17, but the probabilistic values put it in the week 51-7 range. Could the code to generate the point forecast not be dealing with the New Year's transition correctly?

**Comment by nickreich** [comment]
Yes. I'm on a fix for this. Should be committed later today. Should I 
resubmit to the CDC?

Nick

**Comment by craigjmcgowan** [comment]
Yes, that would be great. I've extended the deadline to midnight tonight and it will just overwrite your previous submission.

**Comment by nickreich** [comment]
closed by d4ac828f11c28a36bb374aa8acf20a737e196247
