### ISSUE TITLE
review ensemble file submissions to ensure that they have bins for [53,54) in 2014/2015

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#92]
If they don't have these bins, we need to fix this. Relevant do discussion in https://github.com/FluSightNetwork/cdc-flusight-ensemble/pull/14

**Comment by lepisma** [comment]
I ran tests for this and the files have required bins. Script is [here](https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/test-bins.fish).
