### ISSUE TITLE
'2017 week 53' or '2018 week 01'

### ISSUE THREAD

**Issue by lepisma** [FluSightNetwork/cdc-flusight-ensemble#94]
Right now we have two naming conventions for files for this week (2018 week 01).
- Files from CU follow (probably) the model week style and have names like `EW53-2017-CU_EKF_SIRS.csv`.
- File from LANL follows the epiweek style and have names like `EW01-2018-LANL_DBM.csv`

Is it something to be accounted for in the ensemble scripts or is there a single format to use?

**Comment by nickreich** [comment]
These should all be `EW01-2018-...`.

**Comment by lepisma** [comment]
Closed in f52dba706ac4380b749a326302966252a1884cd5
