### ISSUE TITLE
Possible update needed for week 02 predictions

### ISSUE THREAD

**Issue by lepisma** [FluSightNetwork/cdc-flusight-ensemble#97]
For week 02, in real-time-component-models, we have `/CU_EKF_SIRS/E02-2018-CU_EKF_SIRS.csv` instead of `/CU_EKF_SIRS/EW02-2018-CU_EKF_SIRS.csv` (notice the *EW*). This means the ensemble for this week missed the CU_EKF_SIRS model.

@nickreich any ideas on how to go about this? Specifically, is it possible to resubmit after fixing this issue? If no, then should the csv be _not_ renamed to preserve reproducibility?

PS: Added test to handle such situations in 411e21c92cd9157faa9bde477bae2d3bba6101a4

**Comment by nickreich** [comment]
Thanks for adding a check for filenames. that will be helpful to have in place. I think we could petition to resubmit. I have gone ahead and created a new submission file and updated the filename. 

@tkcy please double-check filenames for next submission!

**Comment by nickreich** [comment]
will commit in a few

**Comment by tkcy** [comment]
Argh, Sorry!

Did it break the whole submission, or just ignore input from this model?  

CU_EKF_SIRS actually has zero weight (according to the report), so if it's the latter, it shouldn't change ensemble result.

**Comment by nickreich** [comment]
Good point! I thought I had checked that but hadn't read carefully enough the EKF and SIRS combo and got confused with CU_EAKFC_SIRS. Trying to update the file anyways, but maybe I won't resubmit the forecast...
